### PR TITLE
Added first interactions with T.A.R.A.L.L.O. database

### PR DESCRIPTION
**Pull request by TsumiYaku**
Referencing #16 

Changes:
- TARALLO login through pytarallo
- Wiping disks only if they're already present into the databse
- Old method previously implemented for TARALLO login removed
- Added config file with URL and token for TARALLO management

TODO:
- Adding disks into TARALLO database

Didn't have the chance to test on a physical disk, only tried on system disk (through --dry) to check if it refused to wipe it (since it wasn't in the database).
Still have to figure out how to add disks through pytarallo (gives me error but it's probably me misusing it)

### CODE REVIEW

**Comment by e-caste** [comment]
It looks good, with 2 exceptions:
- I wouldn't use a long method which loads the config from a json, I'd just call it `config.py` and add a `from config import url, token` (careful, the name `config.py` may be already taken and raise an ImportError)
- I'd remove your personal file names from `.gitignore`, you can ignore them without adding them to git in the first place

**Comment by lvps** [comment]
@e-caste A more professional alternative to the JSON file or config.py file could be dotenv or a simple key=value file in /etc. We could have more than one method, mind you, because a config file is good for development, but a ini file in /etc is better for production (like most *nix program do)

**Comment by TsumiYaku** [comment]
Changed so it uses the dotenv module like suggested by @lvps. Added dotenv to Pipfile.lock.

**Review by TsumiYaku — COMMENTED** [review]
Removed some comments that allowed me to test on sda. Keeping them would have been dangerous for the execution (risk to wipe entire main disk).

**Comment by TsumiYaku** [comment]
Just checked the issues for this repository, the additions in this pull request should also solve #22

**Comment by e-caste** [comment]
Alright, seems good. I'll keep the issue #16 open, so you @TsumiYaku can finish the last thing (which is updating the disk data).
It seems a good time to close #22 though.
Also closing this PR and merging. Good job!

**Pull request merged**
